package com.bgrt.loanrequest;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Prestamo implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Prestamo() {
    }




}